fix: pin eslint-tester to prevent tests bailing
eslint-tester@0.8.2 introduced:

```
TypeError: Cannot read property 'getRuleOptionsSchema' of undefined
```

Pinning to 0.8.1 fixes this. However, eslint-tester has been deprecated; we
should therefore update to ESLint v1.x (#12).

Closes #11.